version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: newmetalbums-backend-prod
    # No external ports - only accessible via internal Docker network
    expose:
      - "8000"
    volumes:
      # Persist database and covers only (no source code mounts)
      - ./data:/app/data
      - ./covers:/app/covers
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newmetalbums-frontend-prod
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    environment:
      # Production mode - nginx proxies all API calls
      - REACT_APP_API_URL=""
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
  covers:
