version: '3.8'

services:
  backend:
    image: ghcr.io/dtorrero/newmetalbums-backend:latest
    container_name: newmetalbums-backend
    ports:
      - "8000:8000"
    volumes:
      # Persist database and covers
      - ./data:/app/data
      - ./covers:/app/covers
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ghcr.io/dtorrero/newmetalbums-frontend:latest
    container_name: newmetalbums-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  data:
  covers:
