version: '3.8'

# Production deployment using pre-built images from GitHub Container Registry
# Multi-architecture support: x64, ARM64, Raspberry Pi

services:
  backend:
    # Pre-built multi-architecture image from GitHub Container Registry
    image: ghcr.io/dtorrero/newmetalbums-backend:latest
    container_name: newmetalbums-backend
    # Backend is NOT exposed externally - only accessible via internal network
    expose:
      - "8000"
    volumes:
      # Persist database and album covers
      - ./data:/app/data
      - ./covers:/app/covers
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - newmetalbums-network

  frontend:
    # Pre-built multi-architecture image from GitHub Container Registry  
    image: ghcr.io/dtorrero/newmetalbums-frontend:latest
    container_name: newmetalbums-frontend
    # Frontend is the ONLY service exposed to the internet
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    environment:
      # Production mode - nginx proxies all API calls to backend
      - REACT_APP_API_URL=""
    networks:
      - newmetalbums-network

# Isolated network for secure internal communication
networks:
  newmetalbums-network:
    driver: bridge

# Persistent volumes for data and covers
volumes:
  data:
  covers:
